In [3]:
from sklearn import linear_model

from sklearn import linear_model

In [4]:
x = [[1],[2],[3],[4],[5],[6]]
y = [0,1,0,1,0,1]

model=linear_model.LogisticRegression()
model.fit(x,y)
print(model.predict([[9]]))

[1]


In [5]:
import numpy as np
import random as rd

In [6]:
a1 = [1,2,1,2,1]
arr1 = np.array(a1)
print(arr1)

[1 2 1 2 1]


In [7]:
arr1.shape

(5,)

In [8]:
arr1.dtype

dtype('int64')

In [9]:
arr1.size

5

In [10]:
arr1.itemsize

8

In [11]:
arr1.ndim

1

In [12]:
dict = {"name": ["dhananjay", "dhruv", "hariom"], "branch":["CSE", "CSE", "Neechi jaat"]}
d = np.array(dict)
d

array({'name': ['dhananjay', 'dhruv', 'hariom'], 'branch': ['CSE', 'CSE', 'Neechi jaat']},
      dtype=object)

In [13]:
a2 = np.arange(10)
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a3 = np.arange(10, 20)
a3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
a2 = np.reshape(a2, (2, 5))
a3 = np.reshape(a3, (2, 5))
a2 + a3

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [16]:
np.concatenate((a2, a3), axis = 0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### 

In [17]:
a2 - a3

array([[-10, -10, -10, -10, -10],
       [-10, -10, -10, -10, -10]])

In [18]:
np.max(a2)

np.int64(9)

In [19]:
np.max(a2, axis = 1)

array([4, 9])

In [20]:
a2 / a3

array([[0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429],
       [0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421]])

In [21]:
np.random.rand(5,4)

array([[0.95304553, 0.62716082, 0.56779624, 0.77556979],
       [0.5044138 , 0.27811964, 0.45396056, 0.37600917],
       [0.22460034, 0.64951753, 0.92043577, 0.06927645],
       [0.01842326, 0.25959263, 0.61813707, 0.93167589],
       [0.93781826, 0.01606046, 0.2054308 , 0.98526635]])

In [22]:
np.random.random((5,4))

array([[0.14378709, 0.93783359, 0.06543588, 0.1743996 ],
       [0.63791617, 0.4950724 , 0.33449144, 0.4912427 ],
       [0.7506818 , 0.32213298, 0.89152813, 0.69176948],
       [0.64706301, 0.15186012, 0.90312323, 0.8328709 ],
       [0.80561155, 0.13787366, 0.05324965, 0.91063968]])

In [23]:
np.random.randn(5)

array([-1.40440944, -1.50669849,  0.06554492, -0.13889104,  1.92252663])

In [24]:
np.random.randint(5)

0

In [25]:
np.random.randint(1,5,(2,3))

array([[3, 2, 1],
       [4, 3, 4]], dtype=int32)

In [26]:
np.random.seed(10)
a = np.random.randint(1,10)
print(a)

5


In [27]:
l = list(range(100))
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [28]:
np.random.choice(l)

np.int64(15)